[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.test]
src = 'test/foundry'

[rpc_endpoints]
canto = "${CANTO_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config